Updated .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -168,30 +168,31 @@ deploy-production:
     - echo "Configuring live environment"
     - >
       ssh gitlab-ci@$DEPLOY_HOST "
-      if [ -d $DEPLOY_DIR_BASE/live ] && [ -n "$(ls -A $DEPLOY_DIR_BASE/live)" ] && [ $(ls -d $DEPLOY_DIR_BASE/live/* | grep ^d | wc -l) -eq 1 ]; then
-        PREVIOUS_VERSION=\$(ls -d $DEPLOY_DIR_BASE/live/*/)
-        PREVIOUS_VERSION=\${PREVIOUS_VERSION%?}
-        PREVIOUS_VERSION=\${PREVIOUS_VERSION##*/}
-        rsync -a $DEPLOY_DIR_BASE/live/\$PREVIOUS_VERSION $DEPLOY_DIR_BASE/previous/
-        if [ -d $DEPLOY_DIR_BASE/deploy/$VERSION ]; then
-          rsync -a $DEPLOY_DIR_BASE/deploy/$VERSION $DEPLOY_DIR_BASE/live/
-          ln -sfn $DEPLOY_DIR_BASE/live/$VERSION /var/www/$APP_PATH/$APP_NAME/
-          rm -rf $DEPLOY_DIR_BASE/live/\$PREVIOUS_VERSION
+      if [ -d $DEPLOY_DIR_BASE/live ]; then
+        if [ -n \"$(ls -A $DEPLOY_DIR_BASE/live)\" ] && [ $(ls -d $DEPLOY_DIR_BASE/live/* | grep ^d | wc -l) -eq 1 ]; then
+          PREVIOUS_VERSION=\$(ls -d $DEPLOY_DIR_BASE/live/*/)
+          PREVIOUS_VERSION=\${PREVIOUS_VERSION%?}
+          PREVIOUS_VERSION=\${PREVIOUS_VERSION##*/}
+          rsync -a $DEPLOY_DIR_BASE/live/\$PREVIOUS_VERSION $DEPLOY_DIR_BASE/previous/
+          if [ -d $DEPLOY_DIR_BASE/deploy/$VERSION ]; then
+            rsync -a $DEPLOY_DIR_BASE/deploy/$VERSION $DEPLOY_DIR_BASE/live/
+            ln -sfn $DEPLOY_DIR_BASE/live/$VERSION /var/www/$APP_PATH/$APP_NAME/
+            rm -rf $DEPLOY_DIR_BASE/live/\$PREVIOUS_VERSION
+          else
+            echo 'Error: deploy directory does not contain the version named $VERSION'
+            exit 1
+          fi
         else
-          echo 'Error: deploy directory does not contain the version named $VERSION'
-          exit 1
-        fi
-      elif [ -d $DEPLOY_DIR_BASE/live ] && [ -z \$(ls -A $DEPLOY_DIR_BASE/live) ]; then
-        if [ -d $DEPLOY_DIR_BASE/deploy/$VERSION ]; then
-          rsync -a $DEPLOY_DIR_BASE/deploy/$VERSION $DEPLOY_DIR_BASE/live/
-          ln -sfn $DEPLOY_DIR_BASE/live/$VERSION /var/www/$APP_PATH/$APP_NAME/
-        else
-          echo 'Error: deploy directory does not contain the version named $VERSION'
-          exit 1
+          if [ -d $DEPLOY_DIR_BASE/deploy/$VERSION ]; then
+            rsync -a $DEPLOY_DIR_BASE/deploy/$VERSION $DEPLOY_DIR_BASE/live/
+            ln -sfn $DEPLOY_DIR_BASE/live/$VERSION /var/www/$APP_PATH/$APP_NAME/
+          else
+            echo 'Error: deploy directory does not contain the version named $VERSION'
+            exit 1
+          fi
         fi
       else
-        echo 'Error: live directory does not contain only the current version'
-        exit 1
+        echo 'Error: live directory does not exist'
       fi
       "
     # echo "CI_COMMIT_REF_SLUG is: ", $CI_COMMIT_REF_SLUG"
